# Generated by Django 5.0.6 on 2024-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
