# Generated by Django 5.0.6 on 2024-05-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0002_alter_trash_type_delete_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramassage',
            name='collection_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
