# Generated by Django 5.0.6 on 2024-05-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0003_alter_ramassage_collection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='co2',
            field=models.IntegerField(default=1),
        ),
    ]
