# Generated by Django 5.0.6 on 2024-05-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0004_trash_co2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='co2',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
